import { defineStore } from "pinia";

export const useTicketStore = defineStore("tickets", {
  state: () => ({
    categories: [
      {
        title: "Entry Tickets",
        slug: "entry-tickets",
        description:
          "An entry ticket is required to access Indonesia Comic Con 2026.",
        notes: [],
        tickets: [
          {
            title: "General One-Day Pass · Day 1 (3 Oct)",
            slug: "general-one-day-pass-day-1",
            image: "/img/tickets/entry-tickets/general-day-1.jpg",
            // starts_in: "Oct 7, 2025 12:00:00",
            // ends_in: "Oct 25, 2025 23:59:59",
            showStartCountdownLabel: false,
            showEndCountdownLabel: false,
            status: "Coming Soon", // empty string, Coming Soon, Available, Sold out
            disableLink: true,
            button_label: "Get ticket",
            // button_url: "https://www.loket.com/event/iccxinacon2025",
            price: "TBA",
            // price_before_discounted: "Rp130,000",
            is_vip: false,
            day_pass: "One-day pass",
            entrance: "Regular entrance",
            benefits: [],
          },
          {
            title: "General One-Day Pass · Day 2 (4 Oct)",
            slug: "general-one-day-pass-day-2",
            image: "/img/tickets/entry-tickets/general-day-2.jpg",
            // starts_in: "Oct 7, 2025 12:00:00",
            // ends_in: "Oct 26, 2025 23:59:59",
            showStartCountdownLabel: false,
            showEndCountdownLabel: false,
            status: "Coming Soon", // empty string, Coming Soon, Available, Sold out
            disableLink: true,
            button_label: "Get ticket",
            // button_url: "https://www.loket.com/event/iccxinacon2025",
            price: "TBA",
            // price_before_discounted: "Rp130,000",
            is_vip: false,
            day_pass: "One-day pass",
            entrance: "Regular entrance",
            benefits: [],
          },
          {
            title: "General Two-Day Pass",
            slug: "general-two-day-pass",
            image: "/img/tickets/entry-tickets/general-two-day-pass.jpg",
            // starts_in: "Oct 7, 2025 12:00:00",
            // ends_in: "Oct 26, 2025 23:59:59",
            showStartCountdownLabel: false,
            showEndCountdownLabel: false,
            status: "Coming Soon", // empty string, Coming Soon, Available, Sold out
            disableLink: true,
            button_label: "Get ticket",
            // button_url: "https://www.loket.com/event/iccxinacon2025",
            price: "TBA",
            // price_before_discounted: "Rp280,000",
            is_vip: false,
            day_pass: "Two-day pass",
            entrance: "Regular entrance",
            benefits: [],
          },
          {
            title: "Cosplayer One-Day Pass · Day 1 (3 Oct)",
            slug: "cosplayer-one-day-pass-day-1",
            image: "/img/tickets/entry-tickets/cosplayer-day-1.jpg",
            // starts_in: "Oct 7, 2025 12:00:00",
            // ends_in: "Oct 25, 2025 23:59:59",
            showStartCountdownLabel: false,
            showEndCountdownLabel: false,
            status: "Coming Soon", // empty string, Coming Soon, Available, Sold out
            disableLink: true,
            button_label: "Get ticket",
            // button_url: "https://www.loket.com/event/iccxinacon2025",
            price: "TBA",
            is_vip: false,
            day_pass: "One-day pass",
            entrance: "Cosplayer entrance",
            benefits: [],
          },
          {
            title: "Cosplayer One-Day Pass · Day 2 (4 Oct)",
            slug: "cosplayer-one-day-pass-day-2",
            image: "/img/tickets/entry-tickets/cosplayer-day-2.jpg",
            // starts_in: "Oct 7, 2025 12:00:00",
            // ends_in: "Oct 25, 2025 23:59:59",
            showStartCountdownLabel: false,
            showEndCountdownLabel: false,
            status: "Coming Soon", // empty string, Coming Soon, Available, Sold out
            disableLink: true,
            button_label: "Get ticket",
            // button_url: "https://www.loket.com/event/iccxinacon2025",
            price: "TBA",
            is_vip: false,
            day_pass: "One-day pass",
            entrance: "Cosplayer entrance",
            benefits: [],
          },
          {
            title: "VIP Cosplayer",
            slug: "vip-cosplayer",
            image: "/img/tickets/entry-tickets/vip-cosplayer.jpg",
            // starts_in: "Oct 7, 2025 12:00:00",
            // ends_in: "Oct 25, 2025 23:59:59",
            showStartCountdownLabel: false,
            showEndCountdownLabel: false,
            status: "Coming Soon", // empty string, Coming Soon, Available, Sold out
            disableLink: true,
            button_label: "Get ticket",
            // button_url: "https://www.loket.com/event/iccxinacon2025",
            price: "TBA",
            is_vip: true,
            day_pass: "Two-day pass",
            entrance: "VIP entrance",
            benefits: [
              "Fast track entrance.",
              "Access to cosplay lounge, changing room, and storage room.",
            ],
          },
          {
            title: "VIP General",
            slug: "vip-general",
            image: "/img/tickets/entry-tickets/vip-general.jpg",
            // starts_in: "Oct 7, 2025 12:00:00",
            // ends_in: "Oct 25, 2025 23:59:59",
            showStartCountdownLabel: false,
            showEndCountdownLabel: false,
            status: "Coming Soon", // empty string, Coming Soon, Available, Sold out
            disableLink: true,
            button_label: "Get ticket",
            // button_url: "https://www.loket.com/event/iccxinacon2025",
            price: "TBA",
            is_vip: true,
            day_pass: "Two-day pass",
            entrance: "VIP entrance",
            benefits: [
              "Fast track entrance.",
              "Access to VIP lounge.",
              "Merchandise from ICC X INACON.",
            ],
          },
        ],
      },
    ],
  }),

  getters: {
    getTicketCategoryBySlug: (state) => (slug) => {
      const category = state.categories.find((item) => item.slug === slug);
      return category ? { category } : {};
    },
  },
});
