import type { H3Event } from "h3";
import { LOCALE_CODES } from "../../shared/cf-cache-rules";

/**
 * Shared helpers for the in-worker edge cache (Cloudflare Cache API).
 *
 * WHY THIS EXISTS: on the `cloudflare_module` preset a Worker runs BEFORE
 * Cloudflare's cache, so a zone Cache Rule can never cache a Worker-generated
 * response — it only governs the `fetch()` subrequests a Worker makes, and Nuxt
 * renders in-process without any origin fetch. The tell is that Worker
 * responses carry no `cf-cache-status` header at all while static assets show
 * `cf-cache-status: HIT`. Under the old `cloudflare-pages` preset the Pages
 * project acted as an origin and the Cache Rule did work; the 21 Jul 2026
 * migration silently removed every bit of HTML edge caching and pushed CPU from
 * 84 ms to 145 ms per request.
 *
 * `caches.default` IS the same zone cache, so entries written here are still
 * removable with an ordinary purge-by-URL call — no Enterprise plan needed.
 * That is what lets the PM One dashboard invalidate content on publish.
 *
 * See docs/cf-cpu-investigation-2026-07.md for the full measurement.
 */

/** Cookie written by @nuxtjs/color-mode (`colorMode.storageKey`). */
const COLOR_MODE_COOKIE = "events-color-mode";

/** Cookie written by @nuxtjs/i18n (`detectBrowserLanguage.cookieKey`). */
const LOCALE_COOKIE = "i18n_locale";

/**
 * Crawlers and preview fetchers. Two thirds of HTML traffic is a flat tail of
 * ~1,850 article URLs averaging ~12 hits/day, much of it bots — and the Cache
 * API is per-colo, so every colo pays its own MISS per URL *per variant*.
 * Collapsing bots onto the default variant (dark, no locale negotiation) halves
 * their key space and lets bot visits pre-warm the cache humans actually use.
 *
 * Safe because a bot never observes the difference: the colour-mode class is
 * cosmetic, and on "/" a bot that would have been locale-redirected gets a 302,
 * which is never cached (200s only) — so a wrong-variant body cannot stick.
 */
const BOT_UA_RE =
  /bot|crawl|spider|slurp|bingpreview|facebookexternalhit|whatsapp|telegram|linkedin|pinterest|petalbot|ahrefs|semrush|mj12|applebot|bytespider|ccbot|amazonbot|gptbot|claude|perplexity|yandex|baidu|duckduck/i;

/**
 * Marks the cache key on the event so the `cacheControl` server plugin knows
 * this response is worth storing once its body exists.
 */
export const EDGE_CACHE_KEY = "__edgeCacheKey";

/**
 * Set alongside EDGE_CACHE_KEY for HTML paths that are NOT in the cf-cache
 * tables: only a 404 response may be stored under such a key (1 h TTL). This is
 * the guard that lets unknown-path error pages be cached without ever risking a
 * per-visitor 200 (checkout, order status…) entering the cache.
 */
export const EDGE_CACHE_404_ONLY = "__edgeCache404Only";

/**
 * Set on the INNER `/__nuxt_error` render (see the middleware): its 200-shaped
 * response body is the branded 404 page for the original URL, and must be
 * stored as a 404 under the original URL's key.
 */
export const EDGE_CACHE_STORE_404 = "__edgeCacheStore404";

/** Edge TTL for cached 404 pages. Short: it only exists to absorb bot floods
 * and dead links; publishing at the URL purges it exactly anyway. */
export const NOT_FOUND_TTL = "public, max-age=0, s-maxage=3600";

/**
 * Edge TTL for cached HTML redirects. Redirects re-invoked the worker on every
 * request (~11k/20h measured: i18n's 302 on "/" for id-language visitors,
 * routeRules like /ticket→/tickets) even though each one is deterministic —
 * "/"'s key carries the negotiation inputs, and routeRules only change with a
 * deploy, which the x-edge-build check already invalidates.
 */
export const REDIRECT_TTL = "public, max-age=0, s-maxage=3600";

/**
 * Header stamped onto every stored HTML entry and validated on lookup.
 *
 * WHY A HEADER AND NOT PART OF THE KEY: purge-by-URL is an exact match
 * INCLUDING the query string, and the PM One backend can never know the build
 * UUID — so a `__b=<uuid>` key param silently made every dashboard purge a
 * no-op (nothing matched). Discovered 23 Jul 2026, hours after the build id
 * was added to the key. Keeping the key enumerable (`?__cm=dark|light`) and
 * validating the build in the stored entry preserves both properties: a
 * deploy still can never serve HTML that references deleted /_nuxt chunks
 * (mismatch = re-render, the iicc white-screen fix), and the backend can
 * still purge by listing the two variants.
 */
export const EDGE_BUILD_HEADER = "x-edge-build";

/** The running build's id — regenerated by Nuxt on every build. */
export function currentBuildId(event: H3Event): string {
  return useRuntimeConfig(event).app?.buildId ?? "dev";
}

/** HTML pages embed hashed chunk URLs; API/OG payloads do not. */
export function isHtmlPath(pathname: string): boolean {
  return !pathname.startsWith("/api/") && !pathname.startsWith("/_og/");
}

/**
 * The Cloudflare Cache API, or null when unavailable (dev server, `nuxi
 * preview`, node preset, tests). Every caller must treat null as "do nothing" —
 * that is what keeps this whole feature a no-op outside Workers.
 */
export function getEdgeCache(): Cache | null {
  const caches = (globalThis as any).caches;
  return caches?.default ?? null;
}

/**
 * Build the cache key for a request.
 *
 * The key is a real URL on the site's own origin (not a synthetic one) so the
 * backend can purge it by URL with the plain `purge_cache` API.
 *
 * `__cm` disambiguates the colour-mode variants: @nuxtjs/color-mode stores the
 * preference in a cookie and SSR stamps it onto `<html class="dark|light">`, so
 * the HTML genuinely differs per visitor. Without this a dark-mode visitor
 * could pin the cache and every light-mode visitor would get dark HTML. JSON
 * API responses never vary this way, so they keep a clean key and a single
 * cache entry.
 */
export function buildEdgeCacheKey(event: H3Event, url: URL): Request {
  const keyUrl = new URL(url.toString());
  const isBot = BOT_UA_RE.test(getRequestHeader(event, "user-agent") ?? "");

  if (isHtmlPath(keyUrl.pathname)) {
    // NOTE: the build id is deliberately NOT part of this key — it lives in the
    // EDGE_BUILD_HEADER of the stored entry and is validated on lookup instead.
    // See that constant for why (a build id in the key breaks purge-by-URL).
    //
    // Bots (no cookies) always land on the default variant anyway; pinning them
    // there keeps one bot with an odd header from minting extra cache entries.
    const preference = isBot ? undefined : getCookie(event, COLOR_MODE_COOKIE);
    keyUrl.searchParams.set("__cm", preference === "light" ? "light" : "dark");
  }

  // "/" is the one route whose response is negotiated rather than determined by
  // its path: @nuxtjs/i18n's detectBrowserLanguage reads the i18n_locale cookie,
  // falls back to Accept-Language, and either renders the default locale or
  // redirects. Both inputs therefore belong in the key.
  //
  // Note this does NOT reimplement i18n's matching — that would rot silently as
  // the module changes. It records the inputs, so any two requests sharing a key
  // handed i18n identical information and cannot have produced different output.
  //
  // Bots skip the negotiation inputs entirely: a cookieless bot with no (or an
  // exotic) Accept-Language resolves to the default-locale 200, and one that
  // WOULD have been redirected gets a 302 — which is never stored, so the
  // collapsed key cannot pin a wrong-locale body.
  //
  // The variant space is deliberately SMALL AND ENUMERABLE so the PM One
  // backend can purge "/" by listing every combination (homeVariantUrls() in
  // pmone's app/Support/EdgeCache.php — keep both sides in lockstep):
  //   __lc ∈ {none} ∪ LOCALE_CODES   ×   __al ∈ {"-"} or {none, other} ∪ codes
  // When the cookie is present, __al is pinned to "-" because i18n gives the
  // cookie precedence and never consults Accept-Language.
  if (keyUrl.pathname === "/" && !isBot) {
    const cookie = getCookie(event, LOCALE_COOKIE);
    // Clamp to known codes: this is visitor-controlled input, and an arbitrary
    // cookie value would otherwise mint unbounded cache entries.
    const lc = cookie && LOCALE_CODES.includes(cookie) ? cookie : "none";
    keyUrl.searchParams.set("__lc", lc);
    keyUrl.searchParams.set(
      "__al",
      lc === "none" ? normalizeAcceptLanguage(event) : "-",
    );
  }

  return new Request(keyUrl.toString(), { method: "GET" });
}

/**
 * Reduce Accept-Language to the FIRST language this app actually has, e.g.
 * "en-US,en;q=0.9,id;q=0.8,fr;q=0.7" -> "en".
 *
 * First-match only (not the full ordered list) for two reasons: it is what
 * i18n's browser-language detection resolves to — it walks the header in order
 * and settles on the first configured locale — so two requests sharing this
 * value hand i18n equivalent input; and a single value keeps the "/" key space
 * enumerable so the backend can purge the homepage by URL. Theoretical caveat:
 * a client sending q-values out of descending order could disagree with i18n's
 * quality-aware pick, but real browsers always emit q-descending, and the
 * worst case is being served the default-locale 200 instead of a redirect —
 * redirects themselves are never cached, so a wrong-locale body cannot stick.
 */
function normalizeAcceptLanguage(event: H3Event): string {
  const header = getRequestHeader(event, "accept-language");
  if (!header) {
    return "none";
  }

  for (const part of header.split(",")) {
    const tag = part.trim().split(";")[0]?.trim().toLowerCase();
    const language = tag?.split("-")[0];

    if (language && LOCALE_CODES.includes(language)) {
      return language;
    }
  }

  return "other";
}
